# @name create-user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Alerrandro Janio",
  "email": "alerrandro22@gmail.com",
  "password": "12345678"
}

###

# @name authenticate-user
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "alerrandro22@gmail.com",
  "password": "12345678"
}